In [1]:
import numpy as np

In [22]:
a = np.array([1, 2, 3, 4])
b = [(1, 2), (3, 4)]
c = [(1, 2)]

print(a[-1])
print(a[:-1])
print()
print(b[-1])
print(b[:-1])
print()
print(c[-1])
print(c[:-1])
print(len([]))


4
[1 2 3]

(3, 4)
[(1, 2)]

(1, 2)
[]
0


In [3]:
a = np.array([[1, 2], [3, 4],[3, 4]])


print(a.shape)
print(np.mean(a, axis=0))

(3, 2)
[2.33333333 3.33333333]


In [2]:
import numpy as np

a = np.array([2, 1, 4, 3])
b = np.sort(a)
c = np.flip(b)
d = c.tolist()

print(b)
print(c)
print()
print(d)

[1 2 3 4]
[4 3 2 1]

[4, 3, 2, 1]


In [ ]:
dim_row, dim_colm = 3, 2
dist_matrix = (np.random.rand(dim_row, dim_colm)+1)*100
dist_matrix2 = (np.random.rand(dim_row, 1, dim_colm))*100
print(dist_matrix)
print(np.max(dist_matrix2))

b = dist_matrix.tolist()
print(b)
print(len(b))

[[177.66519301 132.30592516]
 [113.49153411 172.05353196]
 [140.73620765 185.10894589]]
93.04955417969796
[[177.66519301304135, 132.30592516437974], [113.49153410694055, 172.05353196387816], [140.7362076509569, 185.1089458854425]]
3


In [1]:
a = [2*i for i in range(1, 10)]

print(len(a))

9


In [ ]:
import math

angle = -10
print(angle)


if angle < 0:
    angle = -angle
    sign = -1
else:
    sign = 1

times = angle/360  #(2*math.pi)
cor = math.floor(times)
correction = cor*360  #*2*math.pi
angle_out = angle - correction

angle_out = sign*angle_out


print(angle_out)

-10
-10


In [15]:
angle = -370

times = angle/360  #(2*math.pi)
cor = math.floor(times)
correction = cor*360  #*2*math.pi
angle_out = angle - correction

print(angle_out)

350


In [2]:
ang = 1.30897735

ang_deg = (ang*180)/(math.pi)
print(ang_deg)

74.99887763321878


In [1]:
import math
r = 0.056/2
deg_val = 200

rad_val = (deg_val*math.pi)/180
met = rad_val*r

print(met)

0.09773843811168245


In [ ]:
a = np.array([2, 1, 4, 3])
b = np.array([3, 4, 5, 6])

num = (a - 1)
de = (b- 2)
m = num / de


print(num)
print(de)
print(m)
print()
print(de*num)
print()
dist = np.sqrt( (b-a)**2 + (b-a)**2)
print(dist)

[1 0 3 2]
[1 2 3 4]
[1.  0.  1.  0.5]

[1 0 9 8]

[1.41421356 4.24264069 1.41421356 4.24264069]


In [ ]:
import math

# Circle
r = 0

# line
x1, y1 = [0, 0]
x2, y2 = [0, 0]

dx = x2 - x1
dy = y2 - y1
dr = math.sqrt(dx**2 + dy**2)
D = x1*y2 - x2*y1

if dy >= 0 :
    sign_val = 1
else:
    dy = -1

delta = 0
x1_inter = D*dy + sign_val*dy*dx*math.sqrt(0)


In [23]:
import random

mu = 0
sigma = 0.5
n = random.gauss(mu, sigma)


print(n)
print([random.gauss(mu, sigma) for i in range(0, 4)])

0.7036882171021264
[-0.5319110621355451, 0.1073802493584566, -0.6164015719190833, -0.4113204833941786]


In [1]:
max(-1, 0)

0

In [3]:
a = [[1, 2], [3, 4]]
b = np.array(a)
c = np.flip(c)

print(c)

[1 2 3 4]


In [8]:
b = 5+10 < 10
if b == 0 :
    b = (-1)

print(b)

-1


In [27]:
a = np.array([1, 2, 8, 9])
b = [(3, 4), (5, 6), (10, 20)]
#b = [(10, 20)]

b_x = []
for i in range(0, len(b)-1) :
    b_x.append( b[i][0] )

x = np.insert(a, 0, b_x)
x_sorted = np.sort(x)

idx_xs = []
for xi in b_x :
    idx_xs.append( np.argwhere(x_sorted == xi).item() )

print(len(b))
print("x = ", x)
print("x sorted = ", x_sorted)
print("Idxs = ", idx_xs)
print(x_sorted.shape[0])
print(len(x_sorted))

3
x =  [3 5 1 2 8 9]
x sorted =  [1 2 3 5 8 9]
Idxs =  [2, 3]
6
6


In [28]:
a = np.array([1, 2, 8, 9])
for i, x in enumerate(a) :
    print(i, x)

0 1
1 2
2 8
3 9


In [30]:
a = np.array([1, 2, 8])
b = np.zeros((3,3))

print(b)
print()
b[:] = a
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 2. 8.]
 [1. 2. 8.]
 [1. 2. 8.]]


In [36]:
a = np.array([1, 2, 8])
b = np.array([3, 4, 5])


c = np.stack((a, b))

print(c)
print(c.shape)
print()

a = [ [(1, 2), (3, 4)], [(5, 6)] ]

print("len a = ", len(a))
print("len a = ", a[0])
for t in a:
    print(t)

[[1 2 8]
 [3 4 5]]
(2, 3)

len a =  2
len a =  [(1, 2), (3, 4)]
[(1, 2), (3, 4)]
[(5, 6)]


In [48]:
a = np.array([1, 2, 8])
b = np.array([3, 4, 5])

c = np.stack((a, b))

l = []
l.append(c)

d = np.stack((a*2, b*2))
l.append(d)

print(len(l))
print(l[1])

dist = np.linalg.norm(c, axis=0)
print(dist)
print()

c = np.stack((a[1:] - a[:-1], b[1:] - b[:-1]))
dist = np.linalg.norm(c, axis=0)
print(dist)
print(np.sum(dist))


2
[[ 2  4 16]
 [ 6  8 10]]
[3.16227766 4.47213595 9.43398113]

[1.41421356 6.08276253]
7.496976092671314


In [ ]:
a = [1, 2, 8]
b = [3, 4, 5]

c = np.stack( (a, b) )
print(c)
print()
d  = np.transpose(c)
print(d)
print(d.shape)
print(d[0])
print()
print(np.argmax(d[0]))

[[1 2 8]
 [3 4 5]]

[[1 3]
 [2 4]
 [8 5]]
(3, 2)
[1 3]

1


In [59]:
a = np.array([[1, 2, 8],  [3, 4, 5]])

b = np.delete(a, 0, axis=1)
print(b)

print()
num = np.where(a == 2)
print(num[0])

val = a[0,:] == 2
val_idx = np.argmax(val)

print()
print(a[0, val_idx])
print(val_idx)

[[2 8]
 [4 5]]

[0]

2
1


In [60]:
a = np.array([1])

print(a.shape)
print(a[0, 0])


(1,)


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [66]:
a = np.array([[1, 2, 8],  [3, 4, 5]])
# a = np.array([1, 1, 2, 8])

# au, indeces, counts = np.unique(a, return_inverse=True, return_counts=True, axis=0)
# au, indeces, counts = np.unique(a, return_inverse=True, return_counts=True)
au, counts = np.unique(a[0, :], return_counts=True)

print(a.shape)
print(au)
print()
# print(indeces)
print()
print(counts)
print(np.max(counts))

(2, 3)
[1 2 8]


[1 1 1]
1


In [71]:
l = [1, 2, 3]
a = np.array([1, 1, 2])
print(l*a)

b = a.reshape( (1, 3) )
print(l*b)
print()

c = a.reshape( (3, 1) )
print(c)
print(l*c)
print()

d = np.squeeze(c)
print(d)
print(l*d)

[1 2 6]
[[1 2 6]]

[[1]
 [1]
 [2]]
[[1 2 3]
 [1 2 3]
 [2 4 6]]

[1 1 2]
[1 2 6]


In [6]:
a = np.array([1, 1, 2])

i = 1
print(a[i])

1


In [24]:
a = np.array([[1, 2, 8],  [3, 4, 5]])
idxs = np.array([0, 0, 2])

b = a[:, idxs]
print(b)
sh = idxs.shape
print(sh[0])
id = idxs.reshape(1, sh[0])
print(id)
print(id.shape)
print(a[:, id[0, :]])
print()

idxs = np.array([[0, 0, 2], [1, 1, 0]])
b = a[:, idxs[:]]
print(b)

print("last")
idxs = np.array([[0, 0, 2], [1, 1, 0]])
b = a[0, idxs[0, :]]
print(b)


[[1 1 8]
 [3 3 5]]
3
[[0 0 2]]
(1, 3)
[[1 1 8]
 [3 3 5]]

[[[1 1 8]
  [2 2 1]]

 [[3 3 5]
  [4 4 3]]]
last
[1 1 8]


In [40]:
matrix = np.array([[1, 2, 8],  [3, 4, 5], [6, 7, 8]])

id_list = np.array([[0, 0, 1],  [1, 1, 2], [2, 2, 2]])
# One row
id_list = np.array([0, 0, 2])
id_list = id_list.reshape(1, sh[0])

print(id_list.shape)

c = np.zeros_like(id_list)
for i in range(0, matrix.shape[0]):

    print()
    print("Iter ", i)
    r_i = matrix[i, id_list[:, i]]
    print("r_i ", r_i)

    c[:, i] = r_i
    print(c)

print()    
print("rsult ")
print(np.sum(c, axis=1))

(1, 3)

Iter  0
r_i  [1]
[[1 0 0]]

Iter  1
r_i  [3]
[[1 3 0]]

Iter  2
r_i  [8]
[[1 3 8]]

rsult 
[12]


In [57]:
a = np.arange(3)
# a = np.array([10, 20, 30])
print(a, a.shape)

# b = np.zeros((3, a.shape[0]), dtype=np.int8)
b = np.zeros((3, a.shape[0]))
b[:] = a

print(b, b.shape)
# print(b[0, :])
print()

rng = np.random.default_rng()
# np.random.shuffle(b)
# c = np.random.Generator.permuted(b, axis=1)  # Don't work

c = rng.permuted(b, axis=1)
print(c)

[0 1 2] (3,)
[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]] (3, 3)

[[0. 1. 2.]
 [2. 0. 1.]
 [1. 2. 0.]]


In [55]:
rng = np.random.default_rng()

x = np.arange(24).reshape(3, 8)
# y = np.random.Generator.permuted(x)
y = rng.permuted(x)

print(y)

[[23  1  0  4  7  6 22  9]
 [ 8  3 19 12  2 21 16 14]
 [15  5 18 11 13 10 17 20]]


In [10]:

# Shuffling a 1D array
arr = np.array([10, 20, 30, 40, 50])
print("Before shuffle:", arr, arr.shape)

np.random.shuffle(arr)
print("After shuffle:", arr)

Before shuffle: [10 20 30 40 50] (5,)
After shuffle: [20 30 40 10 50]


In [13]:
# Shuffling rows of a 2D array
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
print("Before shuffle:")
print(arr_2d, arr_2d.shape)

np.random.shuffle(arr_2d)
print("After shuffle:")
print(arr_2d)

Before shuffle:
[[1 2]
 [3 4]
 [5 6]] (3, 2)
After shuffle:
[[1 2]
 [5 6]
 [3 4]]


In [59]:
idxs = np.array([0.5, 1.3, 2.56])

dec = np.round(idxs)
print(dec)

cl = np.clip(idxs, a_min=0, a_max=2)
print()
print(cl)

[0. 1. 3.]

[0.5 1.3 2. ]


In [1]:
import numpy as np

In [9]:
state_storage = np.zeros((1, 3, 1))
al = [1, 2, 3]

a = np.array(al).reshape((1, 3, 1))
state_storage = np.vstack((state_storage, a))
print(state_storage, state_storage.shape)
print(state_storage[1, 2, 0])

[[[0.]
  [0.]
  [0.]]

 [[1.]
  [2.]
  [3.]]] (2, 3, 1)
3.0


In [20]:
state_storage = np.zeros((1, 2, 1, 3))
al = [1, 2, 3]

a = np.array(al).reshape((1, 1, 1, 3))
state_storage[0, 1,:, :] = al
print(state_storage, state_storage.shape)


print("Stack")
state_storage = np.vstack((state_storage, np.expand_dims(state_storage[0, :,:,:], axis=0) ))

print(state_storage)
print(state_storage.shape)

[[[[0. 0. 0.]]

  [[1. 2. 3.]]]] (1, 2, 1, 3)
Stack
[[[[0. 0. 0.]]

  [[1. 2. 3.]]]


 [[[0. 0. 0.]]

  [[1. 2. 3.]]]]
(2, 2, 1, 3)


In [24]:
state_storage = np.zeros((1, 2, 3))
al = [1, 2, 3]

a = np.array(al).reshape((1, 1, 3))
state_storage[0, 1, :] = al
print(state_storage, state_storage.shape)


print("Stack")
state_storage = np.vstack((state_storage, np.expand_dims(state_storage[0, :, :], axis=0) ))

print(state_storage)
print(state_storage.shape)
print()
print(state_storage[1, 1,:])
print(state_storage[1, 1,:][1])
print(state_storage[1, 1,1])

[[[0. 0. 0.]
  [1. 2. 3.]]] (1, 2, 3)
Stack
[[[0. 0. 0.]
  [1. 2. 3.]]

 [[0. 0. 0.]
  [1. 2. 3.]]]
(2, 2, 3)

[1. 2. 3.]
2.0
2.0


In [2]:
route_list = [([1, 2, 3, 4, 5], [1, 2, 3, 4, 5]), ([6, 7, 8, 9, 10], [6, 7, 8, 9, 10])]

route = route_list[0]
track = [[route[0][i], route[1][i]] for i in range(0, len(route[0]))]

print(track)

[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]]


In [3]:
l = [[1, 2], [3, 4]]

print(l)
l[0] = [5, 6]
print(l)

[[1, 2], [3, 4]]
[[5, 6], [3, 4]]


In [ ]:
a = np.random.rand(5, 1)

print(a)

[[0.29101145]
 [0.40497107]
 [0.95126167]
 [0.52039771]
 [0.31246202]]


In [5]:
a, b, c = [1, 2, 3]
d = [4, 3]
print(a, b, c)

a, b, c, m, n = d + [1, 2, 3]
print(a, b, c, m, n)

1 2 3
4 3 1 2 3


In [8]:
import matplotlib.colors as mcolors

print(mcolors.CSS4_COLORS['dimgray'])

#696969


In [11]:
b = [0 for i in range(0, 3)]

print(b)

[0, 0, 0]


In [20]:
a = np.array([1, 2]).reshape((2,1))
b = np.array([0, 0]).reshape((2,1))

for i in range(0, 3):
    b = np.append(b, a)
    print(b)
    print()

[0 0 1 2]

[0 0 1 2 1 2]

[0 0 1 2 1 2 1 2]



In [30]:
a = np.array([1, 2]).reshape((2,1))
b = np.array([0, 0]).reshape((2,1))

for i in range(0, 3):
    b = np.hstack((b, a))
    print(b, b.shape)
    print()

[[0 1]
 [0 2]] (2, 2)

[[0 1 1]
 [0 2 2]] (2, 3)

[[0 1 1 1]
 [0 2 2 2]] (2, 4)



In [32]:
matrix = np.array([[1, 2, 8],  [3, 4, 5], [6, 7, 8]])

mask = matrix[1, :] == 4
print(mask)
print(np.argmax(mask))

[False  True False]
1


In [6]:
a = np.array([1, 2, 2.9, 3, 4, 5, 5.9, 6])
b = np.array([2.9, 5.9])

mask_1 = np.isin(a, b)
print(mask_1)
print(mask_1.shape)
print()
max_1 = np.argmax(mask_1)
print(max_1)



[False False  True False False False  True False]
(8,)

2


In [1]:
import numpy as np
import math

In [15]:
a = [i for i in range(3,6)]
print(a)
print(math.floor(2.5))

[3, 4, 5]
2


In [9]:
a = [[1, 2], [3, 4], [5, 6], [7, 8]]
b = [[10, 20], [30, 40]]

i = 1
a_init = a[:i+1]
a_end = a[i+1:]

c = a_init + b + a_end

print(c)
print(c[i+1])
print(c[-1])
print(c[-2])



[[1, 2], [3, 4], [10, 20], [30, 40], [5, 6], [7, 8]]
[10, 20]
[7, 8]
[5, 6]


In [13]:
b = [10, 20, 30, 40, 50, 60, 70, 80]

print(len(b))
# b.pop(2)
b.remove(50)
print(b)
print(len(b))
print(b[:3])
print(b[3:])
print()

i = 2
i_new = i + 3 
print(i_new)
print(i)
print(b[i_new])


8
[10, 20, 30, 40, 60, 70, 80]
7
[10, 20, 30]
[40, 60, 70, 80]

5
2
70


In [14]:
b = [[10, 20], [30, 40], [50, 60], [70, 80]]

b.remove([30, 40])
print(b)

[[10, 20], [50, 60], [70, 80]]


In [1]:
import numpy as np
import math

In [19]:
state = math.radians(280)
angle_range = math.radians(60)
num_rays = 5

start_angle = state + angle_range
finish_angle = state - angle_range
angles = np.linspace(start_angle, finish_angle, num_rays, False)    

# Sensor Projection
cos_angles = np.cos(angles)
sin_angles = np.sin(angles)

print(np.degrees(angles))
print(cos_angles)
print(sin_angles)

[340. 316. 292. 268. 244.]
[ 0.93969262  0.7193398   0.37460659 -0.0348995  -0.43837115]
[-0.34202014 -0.69465837 -0.92718385 -0.99939083 -0.89879405]


In [2]:
len([])

print([15, 10])

[15, 10]


In [14]:
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

print(a.shape)
print(a[:2])
print(a[:2][:, 0], a[:2][:, 1])
print(a[:2][:, 0] == 3)
print((a[:2][:, 0] == 3) * (a[:2][:, 1] == 4))
print((a[:2][:, 0] == 3) * (a[:2][:, 1] == 2))
print(np.min(a))

print()
mat = (a[:2][:, 0] == 3) * (a[:2][:, 1] == 2)
print(np.sum(mat))

(4, 2)
[[1 2]
 [3 4]]
[1 3] [2 4]
[False  True]
[False  True]
[False False]
1

0


In [16]:
not(1) == 0

True

In [3]:
a = [1, 2, 3, 4]

print(a[:1+1])

[1, 2]


In [2]:
b = np.array([1, 2, 3, 4])

print(b[:2] < 1)

[False False]


In [1]:
import numpy as np

In [11]:
a1 = np.zeros((3, 2))
a2 = np.ones((3, 2))

b = np.stack((a1, a2), axis=1)

print(a1)
print()
print(b.shape)
print(b[:, 0, :])
print()
print(b[:, 1, :])


[[0. 0.]
 [0. 0.]
 [0. 0.]]

(3, 2, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
a = np.zeros((2, 3))
a[1] = [1, 2, 3]

print(a)
print(a[1,1])

[[0. 0. 0.]
 [1. 2. 3.]]
2.0


In [18]:
a = [1, 2]
b = a + [0]
print(b)

[1, 2, 0]


In [15]:
a1 = np.zeros((3, 1, 2))
a2 = np.ones((3, 1, 2))

b = np.hstack((a1, a2))
c = np.hstack((b, a1))

print(a1)
print()
print(b.shape)
print(b[:, 0, :])
print()
print(b[:, 1, :])
print("Print C ")
print(c.shape, c.shape[0])
print(c[:, 2, :])

[[[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]]

(3, 2, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]
Print C 
(3, 3, 2) 3
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
import datetime
import numpy as np

In [15]:
kp = 0.0002
ku = kp/0.5
tu = 0.1

ki = 0.54*ku/tu

print("ku, tu", ku, tu)
print("kp, ki, kd ", kp, ki)

ku, tu 0.0004 0.1
kp, ki, kd  0.0002 0.00216


In [18]:
kp = 0.0001
ku = kp/0.6
tu = 0.1

ki = 1.2*ku/tu
kd = 3*ku*tu/40

print("ku, tu", ku, tu)
print("kp, ki, kd ", kp, ki, kd)

ku, tu 0.0001666666666666667 0.1
kp, ki, kd  0.0001 0.002 1.25e-06


In [7]:
x_fixed = np.linspace(0, 1.5, 5)

print(x_fixed)

[0.    0.375 0.75  1.125 1.5  ]


In [2]:
a = 3
b = 2
time_1 = np.zeros((a, b, 1))

for i in range(0, a):
    for j in range(0, b):
        time_1[i, j, 0] = 2

print(np.mean(time_1))

2.0


In [21]:
b = np.array([1, 2, 3, 4])
c = np.array([10, 20, 30, 40])

d = np.where(b<3, c, c*100)

print(d)
print(math.radians(80))

[  10   20 3000 4000]
1.3962634015954636


In [17]:
a = -math.exp(-5*abs(0.4))+1

print(a)

0.8646647167633873


In [5]:
import math
import numpy as np

print(abs(-1))
print(2**2)

a = [1.57960011,  1.16072109,  0.74184207,  0.32296305, -0.09591597]
b = [math.degrees(i) for i in a]
print(b)

cos_angles = np.cos(a)
sin_angles = np.sin(a)

print()
print(cos_angles)
print(sin_angles)

x = 0
y = 0
ray_length = 10
rays_x = x + ray_length*cos_angles
rays_y = y + ray_length*sin_angles

print()
print(rays_x)
print(rays_y)

1
4
[90.50441962140057, 66.50441964882458, 42.50441967624858, 18.504419703672582, -5.495580268903419]

[-0.00880367  0.39867833  0.73722522  0.94829918  0.99540359]
[ 0.99996125  0.91709083  0.67564708  0.31737781 -0.09576897]

[-0.08803669  3.98678328  7.37225221  9.48299176  9.95403589]
[ 9.99961247  9.1709083   6.75647078  3.17377808 -0.95768969]
