In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

2025-06-15 19:06:46.996392: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
inner_model = keras.Sequential(
    [
        keras.Input(shape=(3,)),
        keras.layers.Dense(4, activation="relu"),
        keras.layers.Dense(2, activation="relu"),
    ]
)

inner_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 4)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 2)              │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 26 (104.00 B)

 Trainable params: 26 (104.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
# w_layer_1 = inner_model.layers[0].getWeights()[0]
# b_layer_1 = inner_model.layers[0].getWeights()[1]
w_layer_1 = inner_model.layers[0]
# b_layer_1 = inner_model.layers[0].getWeights()[1]

print(w_layer_1)
# print(b_layer_1)

<Dense name=dense_2, built=True>


In [3]:
input = keras.Input(shape=(3,))
fc_1 = keras.layers.Dense(4, name="fc_1_")(input)
relu_1 = keras.layers.ReLU()(fc_1)
fc_2 = keras.layers.Dense(2, name="fc_8_")(relu_1)
layer = keras.layers.Activation('sigmoid')(fc_2)

model_test = keras.Model(inputs=[input], outputs=[layer])

In [14]:
model_test.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)      │ (None, 3)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc_1_ (Dense)                   │ (None, 4)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu (ReLU)                    │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc_8_ (Dense)                   │ (None, 2)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation (Activation)         │ (None, 2)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 26 (104.00 B)

 Trainable params: 26 (104.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
w_layer_1 = model_test.layers[1].get_weights()[0]
b_layer_1 = model_test.layers[1].get_weights()[1]

print(w_layer_1.shape)
print(b_layer_1.shape)

(3, 4)
(4,)


In [24]:
w_layer_1

array([[-0.2036553 , -0.5183129 ,  0.359612  ,  0.6282108 ],
       [-0.75627244, -0.36347657, -0.3021195 , -0.5239495 ],
       [ 0.30628037,  0.10281861,  0.17690933, -0.12840885]],
      dtype=float32)

In [25]:
print(b_layer_1)

[0. 0. 0. 0.]


In [33]:
relu_1_layer = model_test.layers[2]
relu_1_layer_weights =relu_1_layer.weights

print(relu_1_layer)
print(len(relu_1_layer_weights))

<ReLU name=re_lu, built=True>
0


In [26]:
# w_layer_1_np = w_layer_1.numpy()
# b_layer_1_np = b_layer_1.numpy()
# w_layer_1_np = tf.make_ndarray(w_layer_1)
# b_layer_1_np = tf.make_ndarray(b_layer_1)

# print(w_layer_1_np)
# print(b_layer_1_np.shape)

In [4]:

w_params = []
b_params = []
for layer_i in model_test.layers:
    w_len = len(layer_i.weights)

    if w_len != 0 :
        w_layer_i = layer_i.get_weights()[0]
        b_layer_i = layer_i.get_weights()[1]
        
        w_params.append(w_layer_i)
        b_params.append(b_layer_i)

print(len(w_params))
print(len(b_params))

2
2


In [5]:
from DRL2 import numpy_layers

In [12]:
# from DRL2 import numpy_layers

model_np = numpy_layers.model_dummy()
model_np.initialization(w_params, b_params)

in1 = np.ones((3))
in1 = np.random.rand((3))
model_np_output = model_np.compute(in1)

model_test.compile()
predict1 = model_test.predict(tf.convert_to_tensor(in1.reshape((1, 3))), verbose=0)

print(model_np_output)
print(predict1)

[0.5        0.50339665]
[[0.49711868 0.50339663]]


/home/camilo/miniconda3/lib/python3.9/site-packages/keras/src/models/functional.py:238: UserWarning: The structure of `inputs` doesn't match the expected structure.
Expected: ['keras_tensor_5']
Received: inputs=Tensor(shape=(1, 3))
  warnings.warn(msg)


In [2]:
import actor_all_18_tf
actor = actor_all_18_tf.load_model()

actor.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 9)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc_1_ (Dense)                   │ (None, 256)            │         2,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu (ReLU)                    │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc_2_ (Dense)                   │ (None, 256)            │        65,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_1 (ReLU)                  │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc_3_ (Dense)                   │ (None, 512)            │       131,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_2 (ReLU)                  │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc_4_ (Dense)                   │ (None, 512)            │       262,656 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_3 (ReLU)                  │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc_5_ (Dense)                   │ (None, 512)            │       262,656 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_4 (ReLU)                  │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc_6_ (Dense)                   │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_5 (ReLU)                  │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc_7_ (Dense)                   │ (None, 256)            │        65,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_6 (ReLU)                  │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc_8_ (Dense)                   │ (None, 2)              │           514 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation (Activation)         │ (None, 2)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 922,882 (3.52 MB)

 Trainable params: 922,882 (3.52 MB)

 Non-trainable params: 0 (0.00 B)

In [3]:
w_params = []
b_params = []
for layer_i in actor.layers:
    w_len = len(layer_i.weights)

    if w_len != 0 :
        w_layer_i = layer_i.get_weights()[0]
        b_layer_i = layer_i.get_weights()[1]
        
        w_params.append(w_layer_i)
        b_params.append(b_layer_i)

print(len(w_params))
print(len(b_params))

8
8


In [9]:
w_test = w_params[0]

print(w_test.shape)
print(w_test.dtype)

(9, 256)
float32


In [ ]:
relu_t = actor.layers[2]

print(relu_t)
print(relu_t.)

<ReLU name=re_lu_77, built=True>


In [8]:
from logging_data import store_data

params_dict = {
    'w_params' : w_params,
    'b_params' : b_params,
}


file_path = './logging_data/'
name = 'actor_all_18_np_params'
store_data.save_time_data_pickle(name, params_dict, path=file_path)

Pickle File Saved as  ./logging_data/actor_all_18_np_params


'./logging_data/actor_all_18_np_params'

In [ ]:
from logging_data import store_data


w_params_list = [arr.tolist() for arr in w_params]
b_params_list = [arr.tolist() for arr in b_params]

params_dict = {
    'w_params' : w_params_list,
    'b_params' : b_params_list,
}


file_path = './logging_data/'
name = 'actor_all_18_np_params_list'
store_data.save_time_data_pickle(name, params_dict, path=file_path)

In [18]:
import actor_all_18_tf
from DRL2 import numpy_layers
actor = actor_all_18_tf.load_model()


in1 = np.random.rand((9))

print("init type ", in1.dtype)
# numpy model
model_np = numpy_layers.model_all_18()
model_np.initialization(w_params, b_params)
output_np = model_np.compute(in1)
output_np = output_np.astype(np.float32)
# Model
in1_input = tf.convert_to_tensor(in1.reshape((1, 9)))
action = actor.predict(in1_input, verbose=0)

print("Actor output ", action, action.dtype)
print("Model np output ", output_np, output_np.dtype)

init type  float64
Actor output  [[0.99999344 0.9996823 ]] float32
Model np output  [0.99999344 0.9996823 ] float32


/home/camilo/miniconda3/lib/python3.9/site-packages/keras/src/models/functional.py:238: UserWarning: The structure of `inputs` doesn't match the expected structure.
Expected: ['keras_tensor_238']
Received: inputs=Tensor(shape=(1, 9))
  warnings.warn(msg)


In [2]:
# LOADING PARAMS
from logging_data import store_data

import actor_all_18_tf
from DRL2 import numpy_layers
actor = actor_all_18_tf.load_model()


in1 = np.random.rand((9))

# numpy model
params_name = './logging_data/actor_all_18_np_params'
data_dict = store_data.load_time_data_pickle(params_name)

w_params = data_dict['w_params']
b_params = data_dict['b_params']
model_np = numpy_layers.model_all_18()
model_np.initialization(w_params, b_params)
output_np = model_np.compute(in1)

# Model
in1_input = tf.convert_to_tensor(in1.reshape((1, 9)))
action = actor.predict(in1_input, verbose=0)

print("Actor output ", action)
print("Model np output ", output_np)

Actor output  [[0.99997723 0.989761  ]]
Model np output  [0.99997724 0.98976104]


/home/camilo/miniconda3/lib/python3.9/site-packages/keras/src/models/functional.py:238: UserWarning: The structure of `inputs` doesn't match the expected structure.
Expected: ['keras_tensor']
Received: inputs=Tensor(shape=(1, 9))
  warnings.warn(msg)
